name: Update Travis File

on:
  schedule:
    - cron: "00 00 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: python -m pip install --upgrade pip feedparser
    - name: Update Travis File
      run: ./build.sh -t
    - name: Push our changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MSG: "Update Travis File with newest Linux releases"
      run: |
        git config user.name "Maxime Ripard"
        git config user.mail "mripard@kernel.org"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git add .travis.yml
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
